#!/bin/bash
#
# setup script (v3.2: Hybrid File Generator - Corrected Paths)
#

DOTFILES_DIR=~/dotfiles

echo "💪 魂をPCに宿らせるぜ！（v3.2 ハイブリッド生成モード）"

# --- 1. 最強の .zshrc を自動生成する ---
echo "--- .zshrcを自動生成中... ---"
rm -f ~/.zshrc # まず、古い.zshrcがあれば削除

{
  echo "# --- This file is auto-generated by dotfiles/setup.sh ---"
  echo "# --- DO NOT EDIT THIS FILE DIRECTLY ---"
  echo ""
  
  if [ -f ~/.bashrc ]; then
    echo "# --- 既存の .bashrc (ROSの設定など) を読み込み ---"
    cat ~/.bashrc
    echo ""
  fi

  # ★★★ここを君の構成に修正！★★★
  # 君のzsh設定（Preztoのローダーとか）をまるごと取り込む
  if [ -f "$DOTFILES_DIR/zsh/.zshrc" ]; then
    echo "# --- kokkoの最強ZSH設定 (Prezto, P10k) を読み込み ---"
    cat "$DOTFILES_DIR/zsh/.zshrc"
    echo ""
  fi
  
} >> ~/.zshrc # 出来上がった内容を ~/.zshrc に書き出す

echo "✅ 最強の .zshrc が生成されたぜ！"


# --- 2. 他の設定ファイル（.gitconfigなど）をシンボリックリンクする ---
echo "--- 他の設定ファイルをリンク中... ---"

# 安全にリンクを貼るための関数 (v3と同じ)
create_safe_link() {
  source_path=$1
  link_target=$2
  mkdir -p "$(dirname "$link_target")"
  if [ -e "$link_target" ] && [ ! -L "$link_target" ]; then
    echo "⚠️ $link_target を $link_target.bak にバックアップします。"
    mv "$link_target" "$link_target.bak"
  fi
  rm -f "$link_target"
  ln -s "$source_path" "$link_target"
  echo "✅ $link_target をリンクしました！"
}

# --- 共通でリンクするファイル ---
# ★★★ここを君の構成に修正！★★★
create_safe_link "$DOTFILES_DIR/zsh/.zpreztorc"  "$HOME/.zpreztorc"
create_safe_link "$DOTFILES_DIR/zsh/.p10k.zsh"   "$HOME/.p10k.zsh"
create_safe_link "$DOTFILES_DIR/git/.gitconfig"  "$HOME/.gitconfig"
# ★★★★★★★★★★★★★★★★★★

# --- WSLじゃなければ、Linux専用リンクも実行 ---
if ! grep -qi "microsoft" /proc/version; then
  echo "---"
  echo "🐧 Linux専用設定をリンク中... ---"
  
  # ★★★ここを君の構成に修正！★★★
  create_safe_link "$DOTFILES_DIR/config/mozc"                "$HOME/.config/mozc"
  create_safe_link "$DOTFILES_DIR/vscode/settings.json"  "$HOME/.config/Code/User/settings.json"
  create_safe_link "$DOTFILES_DIR/vscode/snippets"      "$HOME/.config/Code/User/snippets"
  create_safe_link "$DOTFILES_DIR/config/user-dirs.dirs"      "$HOME/.config/user-dirs.dirs"
  # ★★★★★★★★★★★★★★★★★★
else
  echo "🐧 WSLなのでLinux専用設定はスキップします。"
fi

echo ""
echo "✨ リンク作業完了！"